added new level from Max
BryanGraeser/fallen-flame pull request #141
Opened 2020-05-10 23:47 UTC by stallop

2020-05-11 05:55 UTC, lsizemore8 approved these changes
Resolve the conflict but I like it!

2020-05-11 06:57 UTC, BryanGraeser requested changes
`core/assets/jsons/save.json` should not have all files unlocked.

2020-05-11 06:57 UTC, BryanGraeser commented on core/assets/jsons/save.json
> +      "unlocked":   true,
This file should NOT be set to all unlocked. This determines what is initially unlocked in the JAR

2020-05-11 06:57 UTC, BryanGraeser commented on core/assets/jsons/save.json
> +      "unlocked":   true,
You should add your level, but leave everything locked except the first tutorial level

2020-05-12 19:15 UTC, BryanGraeser approved these changes
fixed save issues. gtg

2020-05-12 19:15 UTC, merged