Update enemy textures
BryanGraeser/fallen-flame pull request #94
Opened 2020-04-27 06:23 UTC by ronnie-dumesh

A couple of textures need to be updated, but that's with the designers. It's one-line fixes for me.

This code adds textures to enemy types A and B and adds the fire buddy texture to the player

2020-04-27 18:07 UTC, BryanGraeser requested changes
Couple small changes listed below.

Was hoping rebasing would remove some of the extraneous differences from earlier commits, but it didn't. So yeah, next time try to make a new branch up-to-date with master for changes so the PR doesn't have a bunch of changes listed that aren't really changes.

2020-04-27 18:07 UTC, BryanGraeser commented on core/src/com/fallenflame/game/LevelController.java
> +                }
Why is this necessary? You're making the same function call from levelcontroller's perspective. You don't need to type cast as EnemyTypeBModel, if that's what it is and EnemyTypeBModel overrides update, it will be call the override version. 
You can replace this whole section with `enemy.update(dt);`

2020-04-27 18:07 UTC, BryanGraeser commented on core/src/com/fallenflame/game/enemies/EnemyModel.java
> +
Why? You're overriding it just to call the version you overwrote? You can just delete this

2020-04-27 18:10 UTC, ronnie-dumesh commented on core/src/com/fallenflame/game/enemies/EnemyModel.java
> +
I can't have an override method EnemyTypeBModel.intializeTextures() if the direct parent doesn't have one. So it's not enough for CharacterModel to have initializeTextures(), EnemyModel needs it as well.

2020-04-27 18:14 UTC, ronnie-dumesh commented on core/src/com/fallenflame/game/enemies/EnemyModel.java
> +
Nvm, I tested it out rn and it worked. For some reason the IDE was throwing errors though. I'll remove this

2020-04-27 18:16 UTC, ronnie-dumesh commented on core/src/com/fallenflame/game/LevelController.java
> +                }
Fixed

2020-04-28 00:16 UTC, BryanGraeser approved these changes
gtg

2020-04-28 00:16 UTC, merged